"""Initial models

Revision ID: 24b75d94edfe
Revises: 
Create Date: 2026-02-01 13:07:07.027398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24b75d94edfe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategorien',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('beschreibung', sa.String(length=500), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['kategorien.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kategorien_id'), 'kategorien', ['id'], unique=False)
    op.create_table('lieferanten',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kurzname', sa.String(length=20), nullable=True),
    sa.Column('kontakt_person', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefon', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('strasse', sa.String(length=200), nullable=True),
    sa.Column('plz', sa.String(length=10), nullable=True),
    sa.Column('ort', sa.String(length=100), nullable=True),
    sa.Column('land', sa.String(length=50), nullable=True),
    sa.Column('notizen', sa.String(length=1000), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lieferanten_id'), 'lieferanten', ['id'], unique=False)
    op.create_index(op.f('ix_lieferanten_name'), 'lieferanten', ['name'], unique=True)
    op.create_table('artikel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artikelnummer', sa.String(length=20), nullable=False),
    sa.Column('bezeichnung', sa.String(length=200), nullable=False),
    sa.Column('beschreibung', sa.String(length=1000), nullable=True),
    sa.Column('kategorie_id', sa.Integer(), nullable=True),
    sa.Column('bestand_lager', sa.Integer(), nullable=False),
    sa.Column('bestand_werkstatt', sa.Integer(), nullable=False),
    sa.Column('mindestbestand', sa.Integer(), nullable=True),
    sa.Column('einkaufspreis', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('verkaufspreis', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('einheit', sa.String(length=20), nullable=True),
    sa.Column('lagerort', sa.String(length=100), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=True),
    sa.Column('notizen', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['kategorie_id'], ['kategorien.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artikel_artikelnummer'), 'artikel', ['artikelnummer'], unique=True)
    op.create_index(op.f('ix_artikel_id'), 'artikel', ['id'], unique=False)
    op.create_table('artikel_lieferanten',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artikel_id', sa.Integer(), nullable=False),
    sa.Column('lieferant_id', sa.Integer(), nullable=False),
    sa.Column('lieferanten_artikelnummer', sa.String(length=100), nullable=True),
    sa.Column('einkaufspreis', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lieferzeit_tage', sa.Integer(), nullable=True),
    sa.Column('bevorzugt', sa.Boolean(), nullable=True),
    sa.Column('notizen', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artikel_id'], ['artikel.id'], ),
    sa.ForeignKeyConstraint(['lieferant_id'], ['lieferanten.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artikel_lieferanten_id'), 'artikel_lieferanten', ['id'], unique=False)
    op.create_table('bestand_historie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artikel_id', sa.Integer(), nullable=False),
    sa.Column('art', sa.Enum('ZUGANG', 'ABGANG', 'KORREKTUR', 'UMLAGERUNG', 'INVENTUR', name='bestandart'), nullable=False),
    sa.Column('ort', sa.Enum('LAGER', 'WERKSTATT', name='bestandort'), nullable=False),
    sa.Column('menge', sa.Integer(), nullable=False),
    sa.Column('bestand_vorher', sa.Integer(), nullable=False),
    sa.Column('bestand_nachher', sa.Integer(), nullable=False),
    sa.Column('grund', sa.String(length=200), nullable=True),
    sa.Column('referenz_typ', sa.String(length=50), nullable=True),
    sa.Column('referenz_id', sa.Integer(), nullable=True),
    sa.Column('erfasst_von', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['artikel_id'], ['artikel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bestand_historie_id'), 'bestand_historie', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bestand_historie_id'), table_name='bestand_historie')
    op.drop_table('bestand_historie')
    op.drop_index(op.f('ix_artikel_lieferanten_id'), table_name='artikel_lieferanten')
    op.drop_table('artikel_lieferanten')
    op.drop_index(op.f('ix_artikel_id'), table_name='artikel')
    op.drop_index(op.f('ix_artikel_artikelnummer'), table_name='artikel')
    op.drop_table('artikel')
    op.drop_index(op.f('ix_lieferanten_name'), table_name='lieferanten')
    op.drop_index(op.f('ix_lieferanten_id'), table_name='lieferanten')
    op.drop_table('lieferanten')
    op.drop_index(op.f('ix_kategorien_id'), table_name='kategorien')
    op.drop_table('kategorien')
    # ### end Alembic commands ###
